/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumDeliveryRequestDeliveryStatus } from "./EnumDeliveryRequestDeliveryStatus";
import { PackageModelUpdateManyWithoutDeliveryRequestsInput } from "./PackageModelUpdateManyWithoutDeliveryRequestsInput";

@InputType()
class DeliveryRequestUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestDeliveryStatus,
  })
  @IsEnum(EnumDeliveryRequestDeliveryStatus)
  @IsOptional()
  @Field(() => EnumDeliveryRequestDeliveryStatus, {
    nullable: true,
  })
  deliveryStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destinationAddress?: string | null;

  @ApiProperty({
    required: false,
    type: () => PackageModelUpdateManyWithoutDeliveryRequestsInput,
  })
  @ValidateNested()
  @Type(() => PackageModelUpdateManyWithoutDeliveryRequestsInput)
  @IsOptional()
  @Field(() => PackageModelUpdateManyWithoutDeliveryRequestsInput, {
    nullable: true,
  })
  packages?: PackageModelUpdateManyWithoutDeliveryRequestsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  receiver?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  requestedOn?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sender?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sourceAddress?: string | null;
}

export { DeliveryRequestUpdateInput as DeliveryRequestUpdateInput };
